language: generic

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker-compose -f docker-compose-test.yml build test

script:
  - docker-compose -f docker-compose-test.yml up --exit-code-from test test
  